// frontend/src/components/RevenueChart.vue
<template>
  <div class="chart-card">
    <div class="chart-header">
      <h3>Revenue trend</h3>
      <span class="chart-sub">Last {{ data.length }} months</span>
    </div>
    <svg :viewBox="`0 0 ${width} ${height}`" class="chart-svg" preserveAspectRatio="none">
      <polyline :points="areaPoints" class="area" />
      <polyline :points="linePoints" class="line" />
      <circle
        v-for="(p, i) in plotted"
        :key="i"
        :cx="p.x"
        :cy="p.y"
        r="3.5"
        class="dot"
      />
    </svg>
    <div class="chart-labels">
      <span v-for="d in data" :key="d.month">{{ d.month }}</span>
    </div>
  </div>
</template>

<script setup>
import { computed } from "vue";

const props = defineProps({
  data: { type: Array, required: true }, // [{ month, value }]
});

const width = 560;
const height = 160;
const padding = 12;

const plotted = computed(() => {
  const values = props.data.map((d) => d.value);
  const max = Math.max(...values);
  const min = Math.min(...values);
  const range = max - min || 1;
  const step = (width - padding * 2) / (props.data.length - 1);

  return props.data.map((d, i) => ({
    x: padding + i * step,
    y: height - padding - ((d.value - min) / range) * (height - padding * 2),
  }));
});

const linePoints = computed(() => plotted.value.map((p) => `${p.x},${p.y}`).join(" "));

const areaPoints = computed(() => {
  const line = plotted.value.map((p) => `${p.x},${p.y}`).join(" ");
  const last = plotted.value[plotted.value.length - 1];
  const first = plotted.value[0];
  return `${first.x},${height} ${line} ${last.x},${height}`;
});
</script>

<style scoped>
.chart-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  padding: 20px 24px 16px;
}

.chart-header {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  margin-bottom: 8px;
}

.chart-header h3 {
  font-size: 15px;
}

.chart-sub {
  font-size: 12px;
  color: var(--text-muted);
}

.chart-svg {
  width: 100%;
  height: 160px;
  display: block;
}

.area {
  fill: var(--accent-tint);
  stroke: none;
}

.line {
  fill: none;
  stroke: var(--accent);
  stroke-width: 2.25;
  stroke-linejoin: round;
  stroke-linecap: round;
}

.dot {
  fill: var(--surface);
  stroke: var(--accent);
  stroke-width: 2;
}

.chart-labels {
  display: flex;
  justify-content: space-between;
  padding: 6px 4px 0;
  font-size: 11.5px;
  color: var(--text-muted);
}
</style>

// frontend/src/components/RevenueChart.tsx
import { useMemo, useState } from "react";
import type { RevenuePoint } from "../types";
import styles from "./RevenueChart.module.css";

interface RevenueChartProps {
  data: RevenuePoint[];
}

const WIDTH = 560;
const HEIGHT = 200;
const PADDING = 16;

function money(n: number): string {
  return `$${Math.round(n).toLocaleString()}`;
}

export default function RevenueChart({ data }: RevenueChartProps) {
  const [hover, setHover] = useState<number | null>(null);

  const { plotted, max, min } = useMemo(() => {
    const values = data.map((d) => d.value);
    const mx = Math.max(...values, 0);
    const mn = Math.min(...values, 0);
    const range = mx - mn || 1;
    const step = data.length > 1 ? (WIDTH - PADDING * 2) / (data.length - 1) : 0;
    return {
      max: mx,
      min: mn,
      plotted: data.map((d, i) => ({
        x: PADDING + i * step,
        y: HEIGHT - PADDING - ((d.value - mn) / range) * (HEIGHT - PADDING * 2),
        ...d,
      })),
    };
  }, [data]);

  const linePoints = plotted.map((p) => `${p.x},${p.y}`).join(" ");
  const areaPoints =
    plotted.length > 0
      ? `${plotted[0].x},${HEIGHT} ${linePoints} ${plotted[plotted.length - 1].x},${HEIGHT}`
      : "";

  const latest = data[data.length - 1]?.value ?? 0;
  const prev = data[data.length - 2]?.value ?? latest;
  const momDelta = prev ? ((latest - prev) / prev) * 100 : 0;
  const up = momDelta >= 0;

  const active = hover != null ? plotted[hover] : null;

  return (
    <div className={styles.chartCard}>
      <div className={styles.chartHeader}>
        <div>
          <h3>Revenue trend</h3>
          <span className={styles.chartSub}>Last {data.length} months</span>
        </div>
        <div className={styles.headline}>
          <span className={styles.headValue}>{money(latest)}</span>
          <span className={`${styles.headDelta} ${up ? styles.up : styles.down}`}>
            {up ? "▲" : "▼"} {Math.abs(momDelta).toFixed(1)}% MoM
          </span>
        </div>
      </div>

      <div className={styles.plot}>
        <svg viewBox={`0 0 ${WIDTH} ${HEIGHT}`} className={styles.chartSvg} preserveAspectRatio="none">
          {[0.25, 0.5, 0.75].map((f) => (
            <line
              key={f}
              x1={PADDING}
              x2={WIDTH - PADDING}
              y1={PADDING + f * (HEIGHT - PADDING * 2)}
              y2={PADDING + f * (HEIGHT - PADDING * 2)}
              className={styles.grid}
            />
          ))}
          <polyline points={areaPoints} className={styles.area} />
          <polyline points={linePoints} className={styles.line} />
          {active && <line x1={active.x} x2={active.x} y1={PADDING} y2={HEIGHT - PADDING} className={styles.guide} />}
          {plotted.map((p, i) => (
            <circle key={p.month} cx={p.x} cy={p.y} r={hover === i ? 5 : 3.5} className={styles.dot} />
          ))}
          {/* invisible hit areas */}
          {plotted.map((p, i) => (
            <rect
              key={`hit-${p.month}`}
              x={p.x - WIDTH / data.length / 2}
              y={0}
              width={WIDTH / data.length}
              height={HEIGHT}
              fill="transparent"
              onMouseEnter={() => setHover(i)}
              onMouseLeave={() => setHover(null)}
            />
          ))}
        </svg>

        {active && (
          <div
            className={styles.tooltip}
            style={{ left: `${(active.x / WIDTH) * 100}%`, top: `${(active.y / HEIGHT) * 100}%` }}
          >
            <strong>{money(active.value)}</strong>
            <span>{active.month}</span>
          </div>
        )}

        <div className={styles.axisMax}>{money(max)}</div>
        <div className={styles.axisMin}>{money(min)}</div>
      </div>

      <div className={styles.chartLabels}>
        {data.map((d) => (
          <span key={d.month}>{d.month}</span>
        ))}
      </div>
    </div>
  );
}
