// frontend/src/views/AdminPanel.tsx
import { useEffect, useState } from "react";
import axios from "axios";
import AppSidebar from "../components/AppSidebar";
import AppTopbar from "../components/AppTopbar";
import api from "../api/client";
import { useAuth } from "../context/AuthContext";
import type { UserRecord, PendingRequest, Role } from "../types";
import styles from "./AdminPanel.module.css";

function errorMessage(err: unknown, fallback: string): string {
  if (axios.isAxiosError(err)) {
    const data = err.response?.data as { error?: string } | undefined;
    return data?.error || fallback;
  }
  return fallback;
}

export default function AdminPanel() {
  const { user, isSuperAdmin } = useAuth();
  const currentUid = user?.uid;

  const [users, setUsers] = useState<UserRecord[]>([]);
  const [requests, setRequests] = useState<PendingRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [busyUid, setBusyUid] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    setError("");
    try {
      const [u, r] = await Promise.all([
        api.get<{ users: UserRecord[] }>("/users"),
        api.get<{ requests: PendingRequest[] }>("/requests"),
      ]);
      setUsers(u.data.users);
      setRequests(r.data.requests);
    } catch (err) {
      setError("Couldn't load users. Is the backend running?");
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
  }, []);

  async function approve(r: PendingRequest) {
    setBusyUid(r.uid);
    try {
      await api.post(`/requests/${r.uid}/approve`);
      await load();
    } catch (err) {
      window.alert(errorMessage(err, "Failed to approve"));
    } finally {
      setBusyUid(null);
    }
  }

  async function deny(r: PendingRequest) {
    if (!window.confirm(`Deny ${r.email}? Their login will be disabled.`)) return;
    setBusyUid(r.uid);
    try {
      await api.post(`/requests/${r.uid}/deny`);
      await load();
    } catch (err) {
      window.alert(errorMessage(err, "Failed to deny"));
    } finally {
      setBusyUid(null);
    }
  }

  async function changeRole(target: UserRecord, role: Role) {
    setBusyUid(target.uid);
    try {
      await api.patch(`/users/${target.uid}/role`, { role });
      setUsers((prev) => prev.map((u) => (u.uid === target.uid ? { ...u, role } : u)));
    } catch (err) {
      window.alert(errorMessage(err, "Failed to update role"));
    } finally {
      setBusyUid(null);
    }
  }

  function formatDate(iso: string | null): string {
    if (!iso) return "—";
    return new Date(iso).toLocaleDateString();
  }

  return (
    <div className="app-shell">
      <AppSidebar />
      <div className="app-content">
        <AppTopbar title="Manage users" />
        <main className={styles.content}>
          <p className={styles.intro}>
            Approve or deny new signups below.{" "}
            {isSuperAdmin ? (
              <>
                As the super admin you can also grant or revoke <strong>admin</strong> access.
              </>
            ) : (
              <>Only the super admin can grant or revoke <strong>admin</strong> access.</>
            )}
          </p>

          {loading ? (
            <p className={styles.state}>Loading…</p>
          ) : error ? (
            <p className={`${styles.state} ${styles.error}`}>{error}</p>
          ) : (
            <>
              {requests.length > 0 && (
                <section className={styles.panel}>
                  <h3>
                    Pending requests <span className={styles.count}>{requests.length}</span>
                  </h3>
                  <ul className={styles.requestList}>
                    {requests.map((r) => (
                      <li key={r.uid}>
                        <div className={styles.who}>
                          <div className={styles.avatar}>{(r.email || "?").slice(0, 2).toUpperCase()}</div>
                          <div>
                            <div className={styles.email}>{r.displayName || r.email}</div>
                            <div className={styles.sub}>{r.email}</div>
                          </div>
                        </div>
                        <div className={styles.requestActions}>
                          <button className={styles.approve} disabled={busyUid === r.uid} onClick={() => approve(r)}>
                            Approve
                          </button>
                          <button className={styles.deny} disabled={busyUid === r.uid} onClick={() => deny(r)}>
                            Deny
                          </button>
                        </div>
                      </li>
                    ))}
                  </ul>
                </section>
              )}

              <table className={styles.userTable}>
                <thead>
                  <tr>
                    <th>User</th>
                    <th>Role</th>
                    <th>Status</th>
                    <th>Joined</th>
                    {isSuperAdmin && <th></th>}
                  </tr>
                </thead>
                <tbody>
                  {users.map((u) => (
                    <tr key={u.uid}>
                      <td>
                        <div className={styles.who}>
                          <div className={styles.avatar}>{(u.email || "?").slice(0, 2).toUpperCase()}</div>
                          <div>
                            <div className={styles.email}>{u.email}</div>
                            {/* <div className={styles.sub}>{u.uid}</div> */}
                          </div>
                        </div>
                      </td>
                      <td>
                        <span className={`${styles.pill} ${(u.isSuperAdmin ? styles.admin : styles[u.role]) || ""}`}>
                          {u.isSuperAdmin ? "super admin" : u.role}
                        </span>
                      </td>
                      <td>
                        <span className={`${styles.pill} ${styles[u.status] || ""}`}>{u.status}</span>
                      </td>
                      <td className={styles.joined}>{formatDate(u.createdAt)}</td>
                      {isSuperAdmin && (
                        <td className={styles.actions}>
                          {u.isSuperAdmin ? (
                            <span className={styles.locked}>locked</span>
                          ) : u.uid === currentUid ? (
                            <span className={styles.locked}>you</span>
                          ) : u.role !== "admin" ? (
                            <button
                              className={styles.promote}
                              disabled={busyUid === u.uid || u.status !== "active"}
                              onClick={() => changeRole(u, "admin")}
                            >
                              Make admin
                            </button>
                          ) : (
                            <button
                              className={styles.demote}
                              disabled={busyUid === u.uid}
                              onClick={() => changeRole(u, "user")}
                            >
                              Revoke admin
                            </button>
                          )}
                        </td>
                      )}
                    </tr>
                  ))}
                </tbody>
              </table>
            </>
          )}
        </main>
      </div>
    </div>
  );
}

// frontend/src/views/AdminPanel.vue
<template>
  <div class="layout">
    <AppSidebar />
    <div class="content-area">
      <AppTopbar title="Manage users" />
      <main class="content">
        <p class="intro">
          You're the super admin — promote or demote anyone below. Everyone else defaults to
          <strong>user</strong> access until you change it.
        </p>

        <p v-if="loading" class="state">Loading…</p>
        <p v-else-if="error" class="state error">{{ error }}</p>

        <table v-else class="user-table">
          <thead>
            <tr>
              <th>User</th>
              <th>Role</th>
              <th>Joined</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="u in users" :key="u.uid">
              <td>
                <div class="user-cell">
                  <div class="avatar">{{ (u.email || "?").slice(0, 2).toUpperCase() }}</div>
                  <div>
                    <div class="email">{{ u.email }}</div>
                    <div class="uid">{{ u.uid }}</div>
                  </div>
                </div>
              </td>
              <td><span class="role-pill" :class="u.role">{{ u.role }}</span></td>
              <td class="joined">{{ formatDate(u.createdAt) }}</td>
              <td class="actions">
                <button
                  v-if="u.role !== 'admin'"
                  class="promote"
                  :disabled="updatingUid === u.uid"
                  @click="changeRole(u, 'admin')"
                >
                  Make admin
                </button>
                <button
                  v-else
                  class="demote"
                  :disabled="updatingUid === u.uid || u.uid === currentUid"
                  @click="changeRole(u, 'user')"
                >
                  Revoke admin
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </main>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import AppSidebar from "../components/AppSidebar.vue";
import AppTopbar from "../components/AppTopbar.vue";
import api from "../api/client";
import { useAuth } from "../composables/useAuth";

const { user } = useAuth();
const currentUid = user.value?.uid;

const users = ref([]);
const loading = ref(true);
const error = ref("");
const updatingUid = ref(null);

async function loadUsers() {
  loading.value = true;
  try {
    const { data } = await api.get("/users");
    users.value = data.users;
  } catch (err) {
    error.value = "Couldn't load users. Is the backend running?";
    console.error(err);
  } finally {
    loading.value = false;
  }
}

async function changeRole(targetUser, role) {
  updatingUid.value = targetUser.uid;
  try {
    await api.patch(`/users/${targetUser.uid}/role`, { role });
    targetUser.role = role;
  } catch (err) {
    alert(err.response?.data?.error || "Failed to update role");
  } finally {
    updatingUid.value = null;
  }
}

function formatDate(iso) {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString();
}

onMounted(loadUsers);
</script>

<style scoped>
.layout { display: flex; min-height: 100vh; }
.content-area { flex: 1; margin-left: var(--sidebar-width); }
.content { padding: 28px 32px 48px; max-width: 1080px; }

.intro {
  font-size: 13.5px;
  color: var(--text-secondary);
  margin: 0 0 20px;
}

.state { color: var(--text-secondary); font-size: 14px; }
.state.error { color: var(--danger); }

.user-table {
  width: 100%;
  border-collapse: collapse;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  overflow: hidden;
}

thead th {
  text-align: left;
  font-size: 12px;
  text-transform: none;
  color: var(--text-muted);
  font-weight: 600;
  padding: 12px 16px;
  border-bottom: 1px solid var(--border);
}

tbody td {
  padding: 12px 16px;
  border-bottom: 1px solid var(--border);
  font-size: 13.5px;
  vertical-align: middle;
}

tbody tr:last-child td { border-bottom: none; }

.user-cell {
  display: flex;
  align-items: center;
  gap: 10px;
}

.avatar {
  width: 30px;
  height: 30px;
  border-radius: 50%;
  background: var(--accent-tint);
  color: var(--accent-strong);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 11px;
  font-weight: 700;
  flex-shrink: 0;
}

.email { font-weight: 500; }
.uid { font-size: 11px; color: var(--text-muted); }
.joined { color: var(--text-secondary); }

.role-pill {
  display: inline-block;
  padding: 3px 10px;
  border-radius: 999px;
  font-size: 12px;
  font-weight: 600;
  text-transform: capitalize;
  background: var(--bg);
  color: var(--text-secondary);
}

.role-pill.admin {
  background: var(--accent-tint);
  color: var(--accent-strong);
}

.actions { text-align: right; }

.actions button {
  border: 1px solid var(--border);
  background: var(--surface);
  padding: 6px 12px;
  border-radius: var(--radius-sm);
  font-size: 12.5px;
  font-weight: 600;
}

.actions .promote {
  border-color: var(--accent);
  color: var(--accent-strong);
}

.actions .demote {
  border-color: var(--danger);
  color: var(--danger);
}

.actions button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
</style>
