// frontend/src/views/Dashboard.vue
<template>
  <div class="layout">
    <AppSidebar />
    <div class="content-area">
      <AppTopbar title="Dashboard" />
      <main class="content">
        <p v-if="loading" class="state">Loading…</p>
        <p v-else-if="error" class="state error">{{ error }}</p>
        <template v-else>
          <section class="stats-grid">
            <StatCard
              v-for="(stat, key, i) in overview.stats"
              :key="key"
              v-bind="stat"
              :featured="i === 0"
            />
          </section>

          <section class="main-grid">
            <RevenueChart :data="overview.revenueTrend" />
            <RecentActivity :items="overview.recentActivity" />
          </section>
        </template>
      </main>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import AppSidebar from "../components/AppSidebar.vue";
import AppTopbar from "../components/AppTopbar.vue";
import StatCard from "../components/StatCard.vue";
import RevenueChart from "../components/RevenueChart.vue";
import RecentActivity from "../components/RecentActivity.vue";
import api from "../api/client";

const overview = ref({ stats: {}, revenueTrend: [], recentActivity: [] });
const loading = ref(true);
const error = ref("");

onMounted(async () => {
  try {
    const { data } = await api.get("/dashboard/overview");
    overview.value = data;
  } catch (err) {
    error.value = "Couldn't load dashboard data. Is the backend running?";
    console.error(err);
  } finally {
    loading.value = false;
  }
});
</script>

<style scoped>
.layout {
  display: flex;
  min-height: 100vh;
}

.content-area {
  flex: 1;
  margin-left: var(--sidebar-width);
}

.content {
  padding: 28px 32px 48px;
  max-width: 1080px;
}

.state {
  color: var(--text-secondary);
  font-size: 14px;
}

.state.error {
  color: var(--danger);
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 16px;
  margin-bottom: 20px;
}

.main-grid {
  display: grid;
  grid-template-columns: 1.6fr 1fr;
  gap: 16px;
}

@media (max-width: 900px) {
  .stats-grid { grid-template-columns: repeat(2, 1fr); }
  .main-grid { grid-template-columns: 1fr; }
}
</style>

// frontend/src/views/Dashboard.tsx
import { useEffect, useState } from "react";
import AppSidebar from "../components/AppSidebar";
import AppTopbar from "../components/AppTopbar";
import ProductHero from "../components/ProductHero";
import StatCard from "../components/StatCard";
import RevenueChart from "../components/RevenueChart";
import CategoryDonut from "../components/CategoryDonut";
import VariantCards from "../components/VariantCards";
import RecentOrders from "../components/RecentOrders";
import api from "../api/client";
import type { DashboardOverview } from "../types";
import styles from "./Dashboard.module.css";

const EMPTY_OVERVIEW: DashboardOverview = {
  product: { name: "", asin: "", price: 0, rating: 0, reviews: 0, stock: 0, unitsLifetime: 0 },
  stats: {},
  revenueTrend: [],
  salesByFinish: [],
  variants: [],
  recentOrders: [],
};

export default function Dashboard() {
  const [overview, setOverview] = useState<DashboardOverview>(EMPTY_OVERVIEW);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const { data } = await api.get<DashboardOverview>("/dashboard/overview");
        if (!cancelled) setOverview(data);
      } catch (err) {
        if (!cancelled) setError("Couldn't load dashboard data. Is the backend running?");
        console.error(err);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className={styles.layout}>
      <AppSidebar />
      <div className={styles.contentArea}>
        <AppTopbar title="Sales overview" />
        <main className={styles.content}>
          {loading ? (
            <p className={styles.state}>Loading…</p>
          ) : error ? (
            <p className={`${styles.state} ${styles.error}`}>{error}</p>
          ) : (
            <>
              <section className={styles.block}>
                <ProductHero product={overview.product} />
              </section>

              <section className={styles.statsGrid}>
                {Object.entries(overview.stats).map(([key, stat], i) => (
                  <StatCard key={key} {...stat} featured={i === 0} />
                ))}
              </section>

              <section className={styles.chartGrid}>
                <RevenueChart data={overview.revenueTrend} />
                <CategoryDonut
                  data={overview.salesByFinish}
                  title="Sales by finish"
                  subtitle="Revenue share · last 30 days"
                />
              </section>

              <section className={styles.block}>
                <VariantCards variants={overview.variants} />
              </section>

              <section className={styles.block}>
                <RecentOrders orders={overview.recentOrders} />
              </section>
            </>
          )}
        </main>
      </div>
    </div>
  );
}
